version: 2

# ==============================
# DEFAULTS FOR JOBS
# ==============================

default job config: &defaults
  working_directory: ~/async_storage

checkout step for each job: &addWorkspace
  attach_workspace:
    at: ~/async_storage

# ==============================
# ENVIRONMENT VARIABLES
# ==============================

default config for js: &js_defaults
  <<: *defaults
  docker:
    - image: circleci/node:10


# ==============================
# CACHE CONFIG
# ==============================

# yarn
save yarn cache: &cache_save_yarn
  name: Saving Yarn cache
  paths:
    - ~/.cache/yarn
  key: yarn-cache-{{ checksum "package.json" }}-{{ arch }}

restore yarn cache: &cache_restore_yarn
  name: Restoring Yarn cache
  keys:
    - yarn-cache-{{ checksum "package.json" }}-{{ arch }}


# ==============================
# JOBS
# ==============================

jobs:
  "Setup environment":
    <<: *js_defaults
    steps:
      - checkout
      - restore-cache: *cache_restore_yarn
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save-cache: *cache_save_yarn
      - persist_to_workspace:
          root: .
          paths: .

  "Test: lint":
    <<: *js_defaults
    steps:
      - *addWorkspace
      - run:
          name: Lint check
          command: yarn test:lint

  "Test: types":
    <<: *js_defaults
    steps:
      - *addWorkspace
      - run:
          name: Typescript check
          command: yarn lerna run test:types

  "Test: unit":
    <<: *js_defaults
    steps:
      - *addWorkspace
      - run:
          name: Unit tests
          command: yarn test:unit


# ==============================
# WORK FLOWS
# ==============================
workflows:
  version: 2
  "Basic tests":
    jobs:
      - "Setup environment"
      - "Test: lint":
          requires:
            - "Setup environment"
      - "Test: types":
          requires:
            - "Setup environment"
      - "Test: unit":
          requires:
            - "Setup environment"
